### ISSUE TITLE
求助！！！

### ISSUE THREAD

**Issue by da-xing-xing666** [xiaohuiduan/opencvstr#2]
老哥，如果我用windows系统 你用IOS系统会有影响么，跑出来的和博客上的不一样。。我这个好像无法清屏，而且跑到一半会断掉

**Comment by xiaohuiduan** [comment]
我用的是linux系统，Windows我没试过，不过你可以想办法进行清屏。
跑到一半会断掉？？？这个情况我没碰到过，你可以把报错的情况贴出来

**Comment by xiaohuiduan** [comment]
> 老哥，如果我用windows系统 你用IOS系统会有影响么，跑出来的和博客上的不一样。。我这个好像无法清屏，而且跑到一半会断掉

我用的是linux系统，Windows我没试过，不过你可以想办法进行清屏。
跑到一半会断掉？？？这个情况我没碰到过，你可以把报错的情况贴出来
